server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/visitor_counter_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 676100nbc
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  
  mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml

  redis:
    host: localhost
    port: 6379
    password: # Your Redis password if any
    database: 7

jwt:
  secret: thisIsAVeryStrongAndSecureSecretKeyForJWTGenerationAndValidation
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

